# Generated by Django 5.0.2 on 2024-02-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_mod_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='age',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='name',
            new_name='username',
        ),
    ]
