# Generated by Django 5.0.2 on 2024-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_rename_age_mod_password_rename_name_mod_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='hlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='mod',
        ),
    ]
